# Site settings
title: Seth Forshee's Blog
email: seth@forshee.me
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog of Seth Forshee
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.forshee.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sethforshee
github_username:  sforshee

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
