# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from

# Site settings
title: "Seth Forshee's Blog"
description: > # this means to ignore newlines until "email:"
   Ramblings of a kernel engineer

email: seth@forshee.me
#blog logo
logo: "/assets/images/sf_logo.jpg"
# blog cover
cover: "/assets/images/IMG_4107.jpg"

name: 'Seth Forshee'
author: 'Seth Forshee'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.forshee.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@sethforshee'

#fill in disqus shortname to use disqus
disqus: sforshee

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/sethforshee
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/sforshee
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
